name: Auto Release on Issue

on:
  issues:
    types: [opened, edited]

jobs:
  release:
    if: contains(github.event.issue.title, 'Release request:') && contains(join(github.event.issue.labels.*.name, ','), 'release')
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Extract version and notes
        id: extract
        run: |
          TITLE="${{ github.event.issue.title }}"
          VERSION=$(echo "$TITLE" | grep -oE '[0-9]+\.[0-9]+\.[0-9]+')
          BODY="${{ github.event.issue.body }}"
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "body<<EOF" >> $GITHUB_OUTPUT
          echo "$BODY" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.extract.outputs.version }}
          name: ${{ steps.extract.outputs.version }}
          body: ${{ steps.extract.outputs.body }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
