name: build

on:
  push:
    tags: ['*']

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        GOOS:
          - linux
          - windows
          - darwin
        GOARCH:
          - amd64
          - arm64
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v4
      with:
        go-version: '1.24.2'
    - name: Build executable
      env:
        GOOS: ${{ matrix.GOOS }}
        GOARCH: ${{ matrix.GOARCH }}
        CGO_ENABLED: 0
      run: |
        if [ "${{ matrix.GOOS }}" = "windows" ]; then
          go build -o kojirou.exe kojirou.go
        else
          go build -o kojirou kojirou.go
        fi
    - name: Upload executable
      uses: actions/upload-artifact@v4
      with:
        name: dist-kojirou-${{ matrix.GOOS }}-${{ matrix.GOARCH }}
        path: kojirou${{ matrix.GOOS == 'windows' && '.exe' || '' }}
